environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "5"
    - nodejs_version: "4"

version: "{build}"
build: off
deploy: off

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm install

test_script:
  - npm test